plugins {
	id 'fabric-loom' version '1.9-SNAPSHOT' // Updated to support newer Gradle versions
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

loom {
	// This tells the dev injector there is no separate 'client' folder


	runs {
		client {
			client()
			configName = "Minecraft Client"
			ideConfigGenerated = true
			runDir = "run"
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:1.21.1"
	mappings "net.fabricmc:yarn:1.21.1+build.3:v2"
	modImplementation "net.fabricmc:fabric-loader:0.18.2"

	// High-performance Fabric API for 1.21.1
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.102.0+1.21.1"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

// Simplified sourceSets to look ONLY at the main folder
sourceSets {
	main {
		java {
			srcDirs = ['src/main/java', 'src/client/java'] // Combines both folders into one 'main' source
		}
		resources {
			srcDirs = ['src/main/resources']
		}
	}
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archives_base_name}"}
	}
}